name: Update some list

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: some generator
        uses: simonecorsi/mawesome@v2
        with:
          api-token: ${{ secrets.PERSONAL_TOKEN }}
          github-email: "41898282+github-actions[bot]@users.noreply.github.com"
          template-path: "template/README.ejs"
          github-name: "github-actions[bot]"
